## What is Tensor

A tensor is a multi-dimensional array of elements with a single data type.

It has two key properties – shape and the data type such as float, integer, or string.

Tensors are the fundamental data structure used by all machine and deep learning algorithms.

They are very similar to NumPy arrays, and they are immutable, which means that they cannot be altered once created. You can only create a new copy with the edits.

Here are some of the key properties of tensors:

Tensors can be of any dimension.

Tensors can be of any data type.

Tensors are immutable.

Tensors are the fundamental data structure used by all machine and deep learning algorithms.

## Creating a Tensor

In [2]:
import tensorflow as tf

string = tf.Variable("This is a String Tensorflow", tf.string)
number = tf.Variable(764, tf.int64)
floating = tf.Variable(4.56, tf.float64)

tf.rank(string) # 0 Dimension Tensor

<tf.Tensor: shape=(), dtype=int32, numpy=0>

## Tensor with Multiple Dim / Rank / Degree

In [3]:
rank1_tensor = tf.Variable(["Sumeet", "Talha", "Hello", "Hi"], tf.string) # 1 Dimension Tensor
rank2_tensor = tf.Variable([[6,7,9], [9,6,8]], [[65,9,7], [3,0,8]], tf.int64) # 2 Dimension Tensor

tf.rank(rank1_tensor)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape of Tensor

No of Values in each Dimension


In [4]:
rank1_tensor.shape

TensorShape([4])

## Changing Shape


In [5]:
tensor1 = tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [6]:
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [7]:
tensor3 = tf.reshape(tensor1, [3, -1]) # -1 Tells the compiler to calculate the dimension at that place
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of Tensor


Variable

Constant

Placeholder

SparseTensor

All are immutable except **Variable**



## Evaluating Tensor

In [8]:
rank1_tensor.numpy()

array([b'Sumeet', b'Talha', b'Hello', b'Hi'], dtype=object)

## Examples


In [9]:
import tensorflow as tf

print(tf.version)

t = tf.zeros([5,5,5,5])
print(t)
# t1 = tf.ones([2,3,1])
# print(t1)

# t2 = tf.reshape(t, [625])
t3 = tf.reshape(t, [125, -1])
print(t3)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\sumee\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>
tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]



## Tensorflow Core Algorithms

Linear Regression

Classification

Clustering

Hidden Markov Models

## Linear Regression


In [10]:
!pip install -q sklearn

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-packag

In [11]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


In [12]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import clear_output
from six.moves import urllib

import tensorflow.compat.v2.feature_column as fc
import tensorflow as tf
